sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 1234
  alioss:
    endpoint: oss-cn-wuhan-lr.aliyuncs.com
    access-key-id: LTAI5tFxNBpyQQamF4ccdFy4
    access-key-secret: Fxh0GgEoSqNGWZAAdcIC29PbWkYIXH
    bucket-name: web-abcde
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 10
  wechat:
    appid: wx674d65c6b746a481
    secret: 4eff9f00c4d91d4a7bdadfb67101033e